CREATE EXTENSION IF NOT EXISTS file_fdw;

CREATE SCHEMA IF NOT EXISTS SA_FINAL_DRAW;
CREATE SCHEMA IF NOT EXISTS SA_FINAL_SCRATCH;


-- Create schema for 3NF if not exists
CREATE SCHEMA IF NOT EXISTS bl_3nf;

