GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA bl_cl TO etl_user;
GRANT SELECT ON ALL TABLES IN SCHEMA bl_cl TO etl_user;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA bl_cl TO etl_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA bl_cl TO etl_user;
GRANT USAGE ON SCHEMA bl_cl TO etl_user;








